export default [
    {
        id: '1',
        title:'Lost Ruins',
        price: 69,
        img:'https://cdn1.epicgames.com/spt-assets/6a10229d28a8493c90a6952984ae06f3/download-lost-ruins-offer-m5inb.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/6a10229d28a8493c90a6952984ae06f3/lost-ruins-1fc2s.png',
            img3:'https://cdn1.epicgames.com/spt-assets/6a10229d28a8493c90a6952984ae06f3/lost-ruins-j0xr3.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/6a10229d28a8493c90a6952984ae06f3/lost-ruins-od0qr.png',
            img5:'https://cdn1.epicgames.com/spt-assets/6a10229d28a8493c90a6952984ae06f3/lost-ruins-14nwu.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/6a10229d28a8493c90a6952984ae06f3/lost-ruins-ubqcp.jpg',  
        },
        developer:'DANGEN Entertainment',
        Data_Wyd:'15.04.22',
        category:'przygodowa',
        opis_glowny:'Lost Ruins is a 2D side-scrolling survival action game. Play as a young girl that has awoken in a strange place with no memories. With the aid of weapons, spells, and the guidance of the mysterious Beatrice, you will explore a dangerous world and topple incredible bosses.',
        opis:{
            h1:'Story',
            a1:'A young girl wakes up in a dimly lit dungeon without any of her memories. Surrounded by horrible, bloodthirsty monsters, the girl is rescued by the magician, Beatrice. With Beatrice’s help, the girl goes on a perilous journey to find answers, and unlock the secrets of the Lost Ruins.',
            h2:'Engage in Combat',
            a2:'Combat in Lost Ruins is both strategic and methodical. Slash away at enemies, burn them to a crisp, or even deflect their projectiles back at them. Arm yourself with a variety of swords, axes and other assorted medieval weaponry, and hack monsters to pieces.',
            h3:'Master Spells',
            a3:'For those with an affinity for magic, Lost Ruins allows you to cast a variety of spells through wands, tonics, and scrolls. Burn monsters, freeze bosses, and heal yourself when in danger. Choose what works for your playstyle and make a magic casting character that’s totally your own.',
            h4:'Choose Your Accessories',
            a4:'The world of Lost Ruins is a dangerous one and being armed to the teeth with awesome weaponry is sometimes not enough. That’s where accessories come in. Accessories are unique pieces of equipment with all manner of effects. One accessory might protect you against fire, while another might heal you when you’re poisoned. The right combination of accessories can create different strategic options for your adventure.',
        },
    },
    {
        id: '2',
        title:'Cat Cafe Manager',
        price: 59,
        img:'https://cdn1.epicgames.com/spt-assets/4fe3c7db294c47e982f032903d40cf28/download-cat-cafe-manager-offer-3q4em.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/4fe3c7db294c47e982f032903d40cf28/cat-cafe-manager-1hbvb.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/4fe3c7db294c47e982f032903d40cf28/cat-cafe-manager-mw5u3.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/4fe3c7db294c47e982f032903d40cf28/cat-cafe-manager-n721c.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/4fe3c7db294c47e982f032903d40cf28/cat-cafe-manager-19fy1.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/4fe3c7db294c47e982f032903d40cf28/cat-cafe-manager-agctr.jpg',
        },
        developer:'Altari Games',
        Data_Wyd:'15.04.22',
        category:'akcja',
        opis_glowny:'Udaj się w podróż do sennego miasteczka Caterwaul Way i odbuduj kocią kawiarnię swojej babci. Wyremontuj lokal, zaprzyjaźnij się z miejscowymi kotami i mieszkańcami, nawiąż trwałe przyjaźnie, rozwikłaj kocie tajemnice i stwórz dom dla dziesiątek wyjątkowych mruczków!',
        opis:{
            h1:'O grze',
            a1:'Poznaj życie właściciela kociej kawiarni w Cat Cafe Manager! Babcia oddała Ci pod opiekę niewielką kawiarnię w sennym miasteczku Caterwaul Way. Twoim zadaniem jest odnowienie lokalu, zaimponowanie miejscowym i zaprzyjaźnienie się z tutejszą kocią populacją. Czas zakasać rękawy, przygotować narzędzia i wziąć się do roboty. Od wyboru strategii, menu i – oczywiście – odpowiednich kotów zależy, czy Twoja kocia kawiarnia będzie na językach mieszkańców.',
            h2:'Kocia kawiarnia',
            a2:'Zgadza się – Caterwaul Way to dom dla wielu nadzwyczajnych mruczków. Ku uciesze i uldze mieszkańców kawiarnia może zostać dla tych zwierząt ostoją. Kto wie, czy ich obecność rozwiąże małomównym języki i pomoże Ci odkryć tajemnice… kotów Caterwaul Way, aby zabrać je z ulicy do nowego domu.',
            h3:'Wyzwania prowadzenia kociej kawiarni',
            a3:`Porzuconą kawiarnię zastajesz w nie najlepszym stanie, ale wystarczy nieco ciężkiej pracy (i pieniędzy), aby znów zachwycała.
            – Wyremontuj kawiarnię, a potem rozbuduj ją i udekoruj tak, jak lubisz. Stwórz tu przytulny zakątek, w którym odprężą się zarówno koty, jak i ludzie.
            – Zorganizuj sprawną załogę, zatrudniając odpowiednie osoby, zarządzając ich obowiązkami i pomagając im w doskonaleniu umiejętności.
            – Twórz własne dania oraz inne pozycje w menu, aby zaspokoić potrzeby gości i zapewnić im jeszcze cudowniejsze wrażenia z wizyty.`,
            h4:'Szukaj przyjaciół i kotów',
            a4:`Dobra kawiarnia to coś więcej, niż tylko smaczne jedzenie i napoje. Chodzi tu o relacje. W Caterwaul Way oznacza to zaprzyjaźnianie się z kotami oraz ludźmi.
            – Nawiązuj i rozwijaj relacje z różnymi mieszkańcami, na przykład z Finleyem, młodym muzykiem marzącym o zawrotnej karierze, oraz Bonnerem, miejscowym kapitanem promu z licznymi niewiarygodnymi historiami w zanadrzu.
            – Opiekuj się miejscowymi kotami, zaprzyjaźnij się z nimi, a potem zaadoptuj je. Każdy dachowiec jest wyjątkowy i na swój sposób wzbogaci Twoją kawiarnię.
            – Dbaj o zadowolenie swoich ludzkich i kocich przyjaciół, aby odblokować wskazówki, które doprowadzą Cię do sekretów Caterwaul Way.`,
            h5:'Pełna życia i rozmruczana mieścina',
            a5:`Caterwaul Way ma długą i tajemniczą historię, którą upamiętniają organizowane tu liczne festiwale. Bierz je pod uwagę, a Twoja kawiarnia stanie się ulubionym miejscem całej okolicy.
            – Zwiedzaj zakątki miasteczka, wchodź w interakcję z mieszkańcami i odkrywaj nowe przepisy oraz szanse rozwoju.
            – Jeśli wszystko pójdzie gładko, możesz odkryć sekret popadającej w ruinę świątyni ku czci dawnego kociego bóstwa, którą wzniesiono w lesie niedaleko Caterwaul Way…`,
            h6:'Pełna życia i rozmruczana mieścina',
            a6:`Caterwaul Way ma długą i tajemniczą historię, którą upamiętniają organizowane tu liczne festiwale. Bierz je pod uwagę, a Twoja kawiarnia stanie się ulubionym miejscem całej okolicy.
            – Zwiedzaj zakątki miasteczka, wchodź w interakcję z mieszkańcami i odkrywaj nowe przepisy oraz szanse rozwoju.
            – Jeśli wszystko pójdzie gładko, możesz odkryć sekret popadającej w ruinę świątyni ku czci dawnego kociego bóstwa, którą wzniesiono w lesie niedaleko Caterwaul Way…`,
        },
        
    },
    {
        id: '3',
        title:'Insurmountable',
        price: 72,
        img:'https://cdn1.epicgames.com/spt-assets/dbc7343b22614dab86a493df7ba9803d/download-insurmountable-offer-eadfm.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/dbc7343b22614dab86a493df7ba9803d/insurmountable-1ozlm.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/dbc7343b22614dab86a493df7ba9803d/insurmountable-1vqbh.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/dbc7343b22614dab86a493df7ba9803d/insurmountable-ybhft.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/dbc7343b22614dab86a493df7ba9803d/insurmountable-1yvji.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/dbc7343b22614dab86a493df7ba9803d/insurmountable-1tlh7.jpg', 
        },
        developer:'DANGEN Entertainment',
        Data_Wyd:'15.04.22',
        category:'przygodowa',
        opis_glowny:'Lost Ruins is a 2D side-scrolling survival action game. Play as a young girl that has awoken in a strange place with no memories. With the aid of weapons, spells, and the guidance of the mysterious Beatrice, you will explore a dangerous world and topple incredible bosses.',
        opis:{
            a1:'A young girl wakes up in a dimly lit dungeon without any of her memories. Surrounded by horrible, bloodthirsty monsters, the girl is rescued by the magician, Beatrice. With Beatrice’s help, the girl goes on a perilous journey to find answers, and unlock the secrets of the Lost Ruins.',
            h1:'Engage in Combat',
            a2:'Combat in Lost Ruins is both strategic and methodical. Slash away at enemies, burn them to a crisp, or even deflect their projectiles back at them. Arm yourself with a variety of swords, axes and other assorted medieval weaponry, and hack monsters to pieces.',
            h3:'Master Spells',
            a3:'For those with an affinity for magic, Lost Ruins allows you to cast a variety of spells through wands, tonics, and scrolls. Burn monsters, freeze bosses, and heal yourself when in danger. Choose what works for your playstyle and make a magic casting character that’s totally your own.',
            h4:'Choose Your Accessories',
            a4:'The world of Lost Ruins is a dangerous one and being armed to the teeth with awesome weaponry is sometimes not enough. That’s where accessories come in. Accessories are unique pieces of equipment with all manner of effects. One accessory might protect you against fire, while another might heal you when you’re poisoned. The right combination of accessories can create different strategic options for your adventure.',
        },
        
    },
    {
        id: '4',
        title:'OPUS: Echo of Starsong',
        price: 59,
        img:'https://cdn1.epicgames.com/spt-assets/b7df2ea1a5624166af9dbde0ca3d1c88/download-opus-echo-of-starsong-offer-dtedh.png?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/b7df2ea1a5624166af9dbde0ca3d1c88/opus-echo-of-starsong-170ul.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/b7df2ea1a5624166af9dbde0ca3d1c88/opus-echo-of-starsong-s47a0.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/b7df2ea1a5624166af9dbde0ca3d1c88/opus-echo-of-starsong-tfmno.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/b7df2ea1a5624166af9dbde0ca3d1c88/opus-echo-of-starsong-1n583.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/b7df2ea1a5624166af9dbde0ca3d1c88/opus-echo-of-starsong-eo6wu.jpg', 
        },
        developer:'DANGEN Entertainment',
        Data_Wyd:'15.04.22',
        category:'akcja',
        opis_glowny:'Lost Ruins is a 2D side-scrolling survival action game. Play as a young girl that has awoken in a strange place with no memories. With the aid of weapons, spells, and the guidance of the mysterious Beatrice, you will explore a dangerous world and topple incredible bosses.',
        opis:{
            a1: '',
            h1:'Echo of Starsong is a visual novel style adventure game. Eda, a girl who can hear mysterious sound waves known as starsong, crosses paths with a young man in search of their source. Together, they venture out to the heart of space to unravel an ancient myth.',
        },
        
    },
{
        id: '5',
        title:'Wildermyth',
        price: 89,
        img:'https://cdn1.epicgames.com/spt-assets/adc5f13f141641f38c65a6bca0c349e6/download-wildermyth-offer-rmvpz.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/adc5f13f141641f38c65a6bca0c349e6/wildermyth-1qudc.jpg',  
        },
        developer:'Worldwalker Games',
        Data_Wyd:'22.04.22',
        category:'strategiczna',
        opis_glowny:'Wildermyth follows heroes over their whole careers, from their pitchfork days to their powerful primes, and on into old age and memory. It’s a party-based procedural storytelling RPG where tactical combat and story decisions will alter your world and reshape your cast of characte',
        opis:{
            h1:'A Myth-Making Tactical RPG',
            a1:'Wildermyth is a character-driven, procedurally-generated tactical RPG. Like the best tabletop roleplaying experiences, Wildermyth gives you choices and answers your every decision with consequences that drive your characters forward.Lead a band of heroes as they grow from reluctant farmers into unique, legendary fighters. Combat unexpected threats and strange monsters across interactive battlefields. Unravel mysteries and share pensive moments in an ever-new fantasy setting that blends hard truths and sacrifice with humor and personal storytelling.',
            h2:'An Imaginative Papercraft World',
            a2:'The Yondering Lands weaves hand-painted 2D characters and scenery into a 3D world to create a luscious, layered landscape, full of detail and surprises. No orcs, elves, or goblins here—but watch out for the telepathic insect-dragons and the clockwork undead.',
            h3:'Extreme Character Depth',
            a3:'Each of your heroes has their own unique generated history, personality, appearance, and relationships with the other heroes—all of which can change over the course of the game as they encounter mysteries and overcome challenges.',
            h4:'Choices That Matter',
            a4:'A hero may choose to trust the enigmatic wolf god, leading to a particularly hair-raising change in their appearance and combat abilities. Or they may choose whether to pursue a romance with a fellow hero, giving each of them new advantages from fighting side by side. Encounters and events have permanent, character-defining effects, letting you craft the arc of each character.',
            h5:'A New Approach to Death',
            a5:'Did your favorite character get one-shotted by a tentacled horror-bear? Choose to let a hero "fall back" with a maiming that will lead to some transformative new paths in their legend, or let them go out in a blaze of glory to be remembered for generations to come.',
        },
    },
{
        id: '6',
        title:'Godlike Burger',
        price: 72,
        img:'https://cdn1.epicgames.com/spt-assets/f42598038b9343e58d27e0a8c0b831b6/download-godlike-burger-offer-8u2uh.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/f42598038b9343e58d27e0a8c0b831b6/godlike-burger-14xrz.png',
            img3:'https://cdn1.epicgames.com/spt-assets/f42598038b9343e58d27e0a8c0b831b6/godlike-burger-1mgy2.png',
            img4:'https://cdn1.epicgames.com/spt-assets/f42598038b9343e58d27e0a8c0b831b6/godlike-burger-1jgz6.png',
            img5:'https://cdn1.epicgames.com/spt-assets/f42598038b9343e58d27e0a8c0b831b6/godlike-burger-1ghrx.png',
            img6:'https://cdn1.epicgames.com/spt-assets/f42598038b9343e58d27e0a8c0b831b6/godlike-burger-16qg2.png',  
        },
        developer:'Liquid Pug',
        Data_Wyd:'21.04.22',
        category:'akcja',
        opis_glowny:'W Godlike Burger zarządzasz najbardziej szaloną restauracją w galaktyce! Ogłuszaj, truj, i zabijaj klientów na różne podstępne sposoby… i przerabiaj ich na mięsko! Jeśli zachowasz ostrożność, kosmiczni klienci nadal będą walić drzwiami i oknami. Kanibalizm? Raczej poezja smaku!',
        opis:{
            h1:'NAJLEPSZE BURGERY WE WSZECHŚWIECIE!',
            a1:'Godlike Burger pozwoli Ci założyć fartuch maniakalnego kucharza, który pichci najlepsze burgery we wszechświecie. Sekretny składnik? Klienci! Prowadź restaurację, przyrządzaj pyszne burgery i zabijaj mnóstwo kosmitów. Ale uważaj – żaden świadek nie może wyjść w jednym kawałku!',
            h2:'ZA DNIA',
            a2:'W ciągu dnia Twoją kosmiczną restaurację odwiedzać będą różne gatunki obcych, aby rozsmakować się w burgerach… albo dać się zabić i przerobić na mielonkę. Lodówki same się nie wypełnią, prawda? Możesz atakować gości niezawodnym tasakiem, bez zbędnych ogródek, albo podejść ich w bardziej kreatywny sposób z użyciem pułapek.',
            h3:'W NOCY',
            a3:'Noc to pora na ulepszanie kuchennego wyposażenia i pułapek, robienie zakupów oraz gotowanie „sekretnych sosów”. Policja nabiera podejrzeń? Przenieś swoją latającą restaurację na inną planetę albo postaw na łapówkę. Gdy próbujesz zyskać miano najsłynniejszej burgerowni w galaktyce, lepiej, gdy nie węszą wokół niej wścibskie gliny.',
        },
    },
{
        id: '7',
        title:'Lila’s Sky Ark',
        price: 49,
        img:'https://cdn1.epicgames.com/spt-assets/673c4d654b2b44d6a1c959a574cf49c3/download-lilas-sky-ark-offer-1nqqt.png?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/673c4d654b2b44d6a1c959a574cf49c3/lilas-sky-ark-1jh7q.png',
            img3:'https://cdn1.epicgames.com/spt-assets/673c4d654b2b44d6a1c959a574cf49c3/lilas-sky-ark-2t63s.png',
            img4:'https://cdn1.epicgames.com/spt-assets/673c4d654b2b44d6a1c959a574cf49c3/lilas-sky-ark-m5f2h.png',
            img5:'https://cdn1.epicgames.com/spt-assets/673c4d654b2b44d6a1c959a574cf49c3/lilas-sky-ark-12qae.png',
            img6:'https://cdn1.epicgames.com/spt-assets/673c4d654b2b44d6a1c959a574cf49c3/lilas-sky-ark-1hco9.png',  
        },
        developer:'Monolith of Minds',
        Data_Wyd:'12.10.22',
        category:'akcja',
        opis_glowny:'Protect a psychedelic world from bizarre beasts and punishing bosses in this poetic mystery filled with secrets, puzzles and music.',
        opis:{
            h1:'Lila’s world is in grave danger. Help her and her friends stop the Conductor’s minions from destroying all things musical and magical!',
            a1:'Explore this dark yet groovy world as you unravel the poetic mystery that is Lila’s story. Discover secrets, solve puzzles, and battle bizarre beasts and punishing bosses as you attempt to unite the Spirits and save the mysterious Sky Island from ruin.Along the way, hunt down alchemy recipes to unlock new weapons. Battle enemies with rocks, Titan Eyes, cluster bombs, and anything else you can throw at them as you wander this music-inspired pixel dreamscape during Lila’s strange yet beautiful journey.',
        },
    },
{
        id: '8',
        title:'MythForce',
        price: 99,
        img:'https://cdn1.epicgames.com/spt-assets/c4099459877a4e47a6b927032f32ed41/download-mythforce-offer-53u2r.png?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/c4099459877a4e47a6b927032f32ed41/mythforce-1ajgd.png',
            img3:'https://cdn1.epicgames.com/spt-assets/c4099459877a4e47a6b927032f32ed41/mythforce-1blmf.png',
            img4:'https://cdn1.epicgames.com/spt-assets/c4099459877a4e47a6b927032f32ed41/mythforce-zhy5o.png',
            img5:'https://cdn1.epicgames.com/spt-assets/c4099459877a4e47a6b927032f32ed41/mythforce-1w2dk.png',
            img6:'https://cdn1.epicgames.com/spt-assets/c4099459877a4e47a6b927032f32ed41/mythforce-12ftp.png',  
        },
        developer:'Beamdog',
        Data_Wyd:'20.04.22',
        category:'rogue-lite',
        opis_glowny:'Inspired by beloved 80s cartoons, MythForce unites swords & sorcery with gripping 1st-person combat in a roguelite adventure fit for Saturday mornings. Brave the dungeon alone or join forces with friends to take on an ever-changing Castle of Evil!',
        opis:{
            h1:'Saturday Mornings Are Back!',
            a1:'Become a cartoon hero in a bodacious 80s fantasy world. Scratch that nostalgic itch with wholesome fun that’s easy to pick up and play (but tough to master).',
            h2:'Immersive 1st-Person Fantasy',
            a2:'Wield legendary weapons and powerful magic to smite hordes of enemies in an immersive fantasy dungeon-crawl through a colorful cartoon castle.',
            h3:'Dungeon-Crawling Fun!',
            a3:'Fresh adventures await with each new attempt to storm the keep! Explore a replayable dungeon with treasure, traps, and terrors lurking around every corner.',
            h4:'Coordinated Co-op Chaos!',
            a4:'Brave the dungeon alone or join forces in co-op mode for up to 4 players. Choose your team wisely— each hero brings unique skills to the fight!',
            h5:'Brave Heroes of Eldryth!',
            a5:'Victoria the valiant Knight joins forces with Rico the charming Rogue, Maggie the wise Mage, and Hawkins the deadly Hunter. Together, they form the legendary team known as… MythForce!',
        },
    },
{
        id: '9',
        title:'Camp Sunshine',
        price: 24,
        img:'https://cdn1.epicgames.com/spt-assets/eda84a7c8a424b9dac5af635d51d1eba/download-camp-sunshine-offer-1iaun.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/eda84a7c8a424b9dac5af635d51d1eba/camp-sunshine-12o1e.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/eda84a7c8a424b9dac5af635d51d1eba/camp-sunshine-12o1e.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/eda84a7c8a424b9dac5af635d51d1eba/camp-sunshine-12o1e.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/eda84a7c8a424b9dac5af635d51d1eba/camp-sunshine-1r9pd.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/eda84a7c8a424b9dac5af635d51d1eba/camp-sunshine-t798f.jpg',  
        },
        developer:'Fossil Games',
        Data_Wyd:'31.10.16',
        category:'horror',
        opis_glowny:'Dropped off at Summer Camp, Jez awakes in the middle of the night to discover blood everywhere...',
        opis:{
            h1:'A Deadly Game of Cat and Mouse!',
            a1:'Camp Sunshine is a 16-bit blood-soaked Horror RPG that pits you as Jez, who is dropped off at Summer Camp. He awakes in the middle of the night to discover blood everywhere, a rampaging killer on the loose dressed in a mascot costume and himself involved in a deadly game of cat and mouse! It is up to you to piece together the puzzle, and relive the past of the Summer Camp Slasher in order to put a stop to this night of terror.',
        },
    },
{
        id: '10',
        title:'FIRES AT MIDNIGHT',
        price: 42,
        img:'https://cdn1.epicgames.com/spt-assets/7ed501a1a5294e7dac7e6dde3e8811f0/download-fires-at-midnight-offer-i1b9t.png?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/7ed501a1a5294e7dac7e6dde3e8811f0/fires-at-midnight-r0wr5.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/7ed501a1a5294e7dac7e6dde3e8811f0/fires-at-midnight-13svk.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/7ed501a1a5294e7dac7e6dde3e8811f0/fires-at-midnight-sqpb8.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/7ed501a1a5294e7dac7e6dde3e8811f0/fires-at-midnight-z1a0p.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/7ed501a1a5294e7dac7e6dde3e8811f0/fires-at-midnight-1gwl3.jpg', 
        },
        developer:'Persona Theory Games',
        Data_Wyd:'10.07.20',
        category:'przygodowa',
        opis_glowny:'In a world where making love without being in love makes you spontaneously combust, the person you adore most may be the one who burns you in Fires at Midnight – a cinematic and interactive visual novel about a couple who struggles to stay together.',
        opis:{
            h1:'ABOUT',
            a1:'You play as Yun, an up-and-coming photographer struggling to balance his life and the relationship with his live-in girlfriend, Chitra. But you’ll also get to experience events from Chitra’s perspective...',
            h2:'YUN & CHITRA',
            a2:'Complete a photobook for Chitra. The photos you choose will reflect what memories Chitra recalls. Find hidden objects through Fires at Midnight’s “Second Layer” – the way our characters truly see the world – and dive deep into the mysteries surrounding the game. Solve puzzles and complete mini-games will aid you to learn the whole story.',
        },
    },
{
        id: '11',
        title:'Hero`s Hour',
        price: 70,
        img:'https://cdn1.epicgames.com/spt-assets/3553687b5efc499aba1cb5231e8a0c56/download-heros-hour-offer-1kfal.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/3553687b5efc499aba1cb5231e8a0c56/heros-hour-ay17d.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/3553687b5efc499aba1cb5231e8a0c56/heros-hour-vefcx.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/3553687b5efc499aba1cb5231e8a0c56/heros-hour-80lud.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/3553687b5efc499aba1cb5231e8a0c56/heros-hour-1ftvp.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/3553687b5efc499aba1cb5231e8a0c56/heros-hour-10wk2.jpg', 
        },
        developer:'ThingOnItsOwn',
        Data_Wyd:'01.03.22',
        category:'strategiczna',
        opis_glowny:'A fast turn-based strategy RPG with real-time combat. Develop your cities and armies, level up your heroes to gain new, powerful spells and skills, and explore the wonders and dangers of the procedurally generated maps as you aim to conquer your enemies before they conquer you.',
        opis:{
            h1:'Introduction',
            a1:'Hero`s Hour is an accessible, yet-deep and content-rich Strategy Roleplaying Game. Take control of your hero, explore the world, build up your town, fight fast-paced battles, level up your hero and amass an army large enough to take out the opponents - before they take you out.',
            h2:'Turn Based + Real Time',
            a2:'While exploring the overworld and developing your town and army are both turn-based, giving you time to think and plan out your next moves, in battles your units will do the best to fight for themselves in real time - all hundreds of them. Cast spells and give attack orders to swing the tide of battle - or just sit back and watch as your might unfolds.',
            h3:'Procedural Generation',
            a3:'Hero`s Hour brings impactful procedural generation to the strategy game formula, ensuring that every time you play, there will be new areas to explore and strange buildings to enhance your hero or army. Seek out obelisks to start you on small procedural quests that send you around the world. You won`t even be able to use the same build order each time you play the same faction.',
        },
    },
{
        id: '12',
        title:'Forgotten Fields',
        price: 45,
        img:'https://cdn1.epicgames.com/spt-assets/9f1a7803961e4b8ab3f5d446b9bc9c7e/download-forgotten-fields-offer-1uffd.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/9f1a7803961e4b8ab3f5d446b9bc9c7e/forgotten-fields-fh2yj.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/9f1a7803961e4b8ab3f5d446b9bc9c7e/forgotten-fields-8qy62.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/9f1a7803961e4b8ab3f5d446b9bc9c7e/forgotten-fields-ina3o.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/9f1a7803961e4b8ab3f5d446b9bc9c7e/forgotten-fields-jx87j.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/9f1a7803961e4b8ab3f5d446b9bc9c7e/forgotten-fields-mu2x8.jpg',  
        },
        developer:'Frostwood Interactive',
        Data_Wyd:'22.02.22',
        category:'przygodowa',
        opis_glowny:'Sid, a struggling writer, travels back to his childhood home one last time before it`s sold off. Visit old friends, relive memories, solve puzzles and play through sections of Sid`s book in this warm game about nostalgia and the passage of time.',
        opis:{
            h1:'WELCOME TO THE PAST',
            a1:'Sid is a writer struggling with writer`s block, attempting to recapture the feelings of inspiration he felt when he was younger. In order to pay the bills, he needs to think up a story and apply for a grant - the deadline is today - a lazy Sunday in the middle of summer.',
            h2:'OLD TIMES AND NOSTALGIC MEMORIES',
            a2:'On this Sunday, his struggle is disturbed by an invitation to attend an unavoidable family obligation - the place Sid grew up in is about to be sold, and his mother wants him to come home for a small party so he can say goodbye to it. With the deadline approaching and his creative juices having frozen, this is not something he`s looking forward to.',
        },
    },
{
        id: '13',
        title:'Call of the Sea',
        price: 69,
        img:'https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_CalloftheSea_OutoftheBlue_S2_1200x1600-db63acf0c479c185e0ef8f8e73c8f0d8?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn2.unrealengine.com/egs-callofthesea-outoftheblue-g1a-01-1920x1080-537366269855.jpg',
            img3:'https://cdn2.unrealengine.com/egs-callofthesea-outoftheblue-g1a-02-1920x1080-8afbacdc26e1.jpg',
            img4:'https://cdn2.unrealengine.com/egs-callofthesea-outoftheblue-g1a-03-1920x1080-2789ebb25f4c.jpg',
            img5:'https://cdn2.unrealengine.com/egs-callofthesea-outoftheblue-g1a-04-1920x1080-9e630ee18ec0.jpg',
            img6:'https://cdn2.unrealengine.com/egs-callofthesea-outoftheblue-g1a-05-1920x1080-a3cad3af2154.jpg', 
        },
        developer:'Out of the Blue',
        Data_Wyd:'08.12.20',
        category:'przygodowa',
        opis_glowny:'Call of the Sea to fantastyczna opowieść pełna tajemnic i miłości, która rozgrywa się na południowym Pacyfiku w latach 30. XX wieku. Eksploruj przepyszną, rajską wyspę, rozwiązuj łamigłówki i odkrywaj sekrety w poszukiwaniu zaginionej ekspedycji swojego męża.',
        opis:{
            h1:'Call of the Sea',
            a1:'W 1934 roku, na odległym krańcu południowego Pacyfiku… Norah przepłynęła ocean, podążając za tropem zaginionej ekspedycji swojego męża. Fale zaprowadziły ją na przepyszną, rajską wyspę – bezimienne, zapomniane miejsce, w którym rozsiane są ślady upadłej cywilizacji.',
            h2:'Odkryj piękno natury',
            a2:'Przemierzaj zakątki zachwycającej, tropikalnej wyspy (starannie opracowanej przy pomocy Unreal Engine 4), na której czekają Cię niesamowite widoki, opuszczone ruiny i magiczne tajemnice.',
            h3:'Poznaj Norah',
            a3:'Zapoznaj się z tym urzekającym studium charakteru kobiety, która poszukuje prawdy na temat zaginięcia jej męża oraz swojej prawdziwej tożsamości. Głosu Norah użyczyła Cissy Jones (Firewatch, The Walking Dead: Season 1).',
            h4:'Zanurz się w głębinie',
            a4:'Daj się wciągnąć fabularnej przygodzie pełnej emocji, napięcia i surrealistycznych niespodzianek.',
            h5:'Znajdź odpowiedzi',
            a5:'Badaj tropy pozostawione przez przebywających tu niegdyś podróżników, ustal, co tak naprawdę się wydarzyło i rozwiąż różne sprytnie zaprojektowane łamigłówki.',
        },
    },
    {
        id: '14',
        title:'Revita',
        price: 61,
        img:'https://cdn1.epicgames.com/spt-assets/45c5c3b3a6264f559309ae985cfb7e1a/download-revita-offer-1k8zk.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/45c5c3b3a6264f559309ae985cfb7e1a/revita-16hy1.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/45c5c3b3a6264f559309ae985cfb7e1a/revita-r58z6.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/45c5c3b3a6264f559309ae985cfb7e1a/revita-1ekrg.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/45c5c3b3a6264f559309ae985cfb7e1a/revita-1vh3j.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/45c5c3b3a6264f559309ae985cfb7e1a/revita-1ajse.jpg',  
        },
        developer:'BenStar',
        Data_Wyd:'21.04.22',
        category:'przygodowa',
        opis_glowny:'In this fast paced twin-stick roguelite platformer, you play as an unnamed child ascending an ominous clocktower in pursuit of their lost memories. Harvest and sacrifice souls to grow your power in order to challenge procedural encounter rooms and intimidating bosses!',
        opis:{
            h1:'About Revita',
            a1:'A fast paced twin-stick roguelite platformer. Climb an ominous clock tower in a series of procedural encounter rooms and past challenging boss fights on your way to reclaiming your lost memory.',
            h2:'Defeat, Heal, Sacrifice!',
            a2:'Exchange health for power in fast paced glass cannon gameplay. Find the right balance of attack and defense as you try, die, repeat and progress up the tower',
            h3:'Unique Runs',
            a3:'Battle through an almost infinite variety of combat encounters in procedurally generated rooms',
            h4:'Unique Powers',
            a4:'Twin stick shooting, dashing and wall sliding are just the beginning - find power-ups and items on each run and upgrade your arsenal',
            h5:'Tweak Your Game',
            a5:'An extensive set of options lets you tweak Revita to your playstyle - slow down time, set an outline colour for enemies to make them easier to track or choose the level of aim assist that feels right for you.',
            h6:'Discover a mysterious world',
            a6:'Explore an underground subway line infested with monsters and filled with colourful characters who will help you on your journey. Travelling from station to station where elevators take you towards the heights of an ever changing clocktower.',
            h7:'Reclaim your lost memory',
            a7:'A nameless child with no memories awakens in the metro with only a vague sense of purpose and desire to reach the distant clocktower, hoping to find answers at the top. On the way they will discover a melancholic world filled with masked characters, monsters and perhaps the answers that the child seeks.',
        },
    },
    {
        id: '15',
        title:'This Is the Police',
        price: 50,
        img:'https://cdn1.epicgames.com/offer/a3fb4c2877a7466b895da9d7fab2bd24/EGS_ThisIsthePolice_WeappyStudio_S2_1200x1600-476af26fb159eb44648447bb9bdc56f1?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn2.unrealengine.com/egs-thisisthepolice-weappystudio-g1a-00-1920x1080-8e8c2b7094b2.jpg',
            img3:'https://cdn2.unrealengine.com/egs-thisisthepolice-weappystudio-g1a-01-1920x1080-b017bf9eebff.jpg',
            img4:'https://cdn2.unrealengine.com/egs-thisisthepolice-weappystudio-g1a-02-1920x1080-e23c90006c95.jpg',
            img5:'https://cdn2.unrealengine.com/egs-thisisthepolice-weappystudio-g1a-03-1920x1080-bdd4233cfbca.jpg',
            img6:'https://cdn2.unrealengine.com/egs-thisisthepolice-weappystudio-g1a-04-1920x1080-73a4c5f82c33.jpg',  
        },
        developer:'Weappy Studio',
        Data_Wyd:'02.08.16',
        category:'akcja',
        opis_glowny:'This Is the Police to gra strategiczno-przygodowa osadzona w mieście, które stacza się na samo dno. Wciel się w rolę surowego komendanta policji Jacka Boyda i zanurz się w historię o przestępstwach i intrygach.',
        opis:{
            h1:'This Is the Police',
            a1:`Zanurz się w historię o korupcji, przestępstwach i intrygach. Wciel się w rolę komendanta policji Jacka Boyda i zmierz się z paskudnym światkiem Freeburga, miasta, które stacza się na sam dół. Czy Jack dotrwa do emerytury z ładnym stosikiem banknotów, czy skończy bez grosza... lub jeszcze gorzej?
                Zarządzaj personelem, reaguj na nagłe sytuacje i badaj przestępstwa w mieście, które jest na skraju chaosu. W podziemiu mafia coraz śmielej oplata swoimi mackami miasto, a burmistrz jest gotów wykorzystać każdą sytuację, żeby odnieść polityczną korzyść.
                Zdecyduj, jak postąpić w miarę rozwoju akcji. Czasami musisz reagować na rozwijającą się sytuację kryzysową na miejscu zbrodni, a kiedy indziej negocjować z bossami przestępczego świata w Freeburgu. Czasami będziesz unikać pytań podczas konferencji prasowych, a czasem nawet odpowiadać na pytania w sądzie. Czy uda Ci się nie wybuchnąć, przynajmniej do czasu, aż uzbierasz wystarczająco dużo na miłe gniazdko na starość?`,
        },
    },
    {
        id: '16',
        title:'Skábma - Snowfall',
        price: 72,
        img:'https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_SkbmaSnowfall_RedStageEntertainment_S4_1200x1600-bf9fb9a660d2e7df58e66377cb84a568?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn2.unrealengine.com/egs-skbmasnowfall-redstageentertainment-g1a-00-1920x1080-f51bd19dbab4.jpg',
            img3:'https://cdn2.unrealengine.com/egs-skbmasnowfall-redstageentertainment-g1a-01-1920x1080-589276e081de.jpg',
            img4:'https://cdn2.unrealengine.com/egs-skbmasnowfall-redstageentertainment-g1a-02-1920x1080-fc1f1bfa79c1.jpg',
            img5:'https://cdn2.unrealengine.com/egs-skbmasnowfall-redstageentertainment-g1a-03-1920x1080-ae19dd7ee711.jpg',
            img6:'https://cdn2.unrealengine.com/egs-skbmasnowfall-redstageentertainment-g1a-04-1920x1080-db196304dc91.jpg', 
        },
        developer:'Red Stage Entertainment',
        Data_Wyd:'22.04.22',
        category:'przygodowa',
        opis_glowny:'Rytm natury jest zagrożony! Wcielasz się w rolę Áilu, młodej Laponki, której zwykłe życie pasterki reniferów przeradza się w niesamowitą przygodę. Okiełznaj moc szamańskiego bębna i duchowych zwierząt, aby walczyć z rozprzestrzeniającym się chaosem!',
        opis:{
            h1:'O grze',
            a1:'Skábma – Snowfall to gra, która w niespotykany dotąd sposób ukazuje historię i kulturę ludu Saamów. Eksploruj piękny, nordycki świat, w którym zamanifestują się stare opowieści, snute przez mieszkańców Północy przy ognisku! Wykaż się sprytem, by rozwiązywać zagadki środowiskowe i mierzyć się z wyzwaniami platformowymi w tej trzecioosobowej fabularnej grze przygodowej.',
            h2:'Ocal swój dom!',
            a2:'Wcielisz się w Áilu, młodego saamskiego pasterza reniferów, który wyrusza na poszukiwania zbiegłej samicy. Tajemnica rosnącego chaosu zaczyna się wyjaśniać, gdy Áilu odkrywa stary, zaczarowany bęben zwany Goavddis. Dla dotkniętych chorobą liczy się każda minuta, a wewnątrz bębna wciąż wybrzmiewa zapomniana wiedza Noadi, saamskich uzdrowicieli.',
            h3:'Bogata fabuła',
            a3:'To wyjątkowa historia o zamieszkującym północny kraniec Europy ludzie, Saami. Oglądaj przerywniki filmowe z lektorem mówiącym w języku północnosaamskim i zanurz się w nowej przygodzie.',
            h4:'Znajome Duchy',
            a4:'Odnajdź czwórkę Znajomych Duchów. Są nimi Skuolfi – sowa, Guovža – niedźwiedź, Čámsa – pstrąg oraz Rieban – lis. Dysponują one różnymi mocami, które wpływają na twoje ruchy oraz możliwości poskromienia chaosu szerzącego się w Laponii.',
            h5:'Uderzaj w bęben',
            a5:'Używaj swojego bębna oraz mocy Znajomych Duchów, by wykrywać niewidzialne elementy ukryte w arktycznej przyrodzie. Podążaj szlakami, które zaprowadzą cię do znajdziek, duchów ludzi oraz drzew – pomogą ci one w pokonywaniu przeszkód i rozwiązywaniu zagadek środowiskowych.',
            h6:'Wciągający świat Północy',
            a5:'Odkrywaj tajemnicze krajobrazy zarówno fizycznych, jak i duchowych światów przy akompaniamencie czarującej muzyki, w tym tradycyjnych saamskich śpiewów (joik) w wykonaniu wielokrotnie nagradzanej wokalistki, Hildy Länsman. Poznaj świat Áilu, odnajdź skarb rodzinny dziadka i dowiedz się, co inni sądzą o saamskiej kulturze. Łap zające i rozmawiaj z duchami, by dowiedzieć się więcej o świecie gry i poznać historie Saamów.',
        },
    },

{
        id: '17',
        title:'Dollhouse',
        price: 47,
        img:'https://cdn1.epicgames.com/spt-assets/bc305b78a8ed460aa9a386532943fce6/download-dollhouse-offer-udjt3.jpg?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/bc305b78a8ed460aa9a386532943fce6/dollhouse-1qf49.png',
            img3:'https://cdn1.epicgames.com/spt-assets/bc305b78a8ed460aa9a386532943fce6/dollhouse-19mrl.png',
            img4:'https://cdn1.epicgames.com/spt-assets/bc305b78a8ed460aa9a386532943fce6/dollhouse-181g8.png',
            img5:'https://cdn1.epicgames.com/spt-assets/bc305b78a8ed460aa9a386532943fce6/dollhouse-w5ujk.png',
            img6:'https://cdn1.epicgames.com/spt-assets/bc305b78a8ed460aa9a386532943fce6/dollhouse-18zlw.png', 
        },
        developer:'Crezan',
        Data_Wyd:'29.10.21',
        category:'horror',
        opis_glowny:'Dollhouse to mrożący krew w żyłach horror à la film noir, który wstrząśnie Tobą do głębi. Przetrwaj przerażającą podróż po umyśle detektyw Marie. Poskładaj w całość swoją przeszłość, a jednocześnie oglądaj się za siebie, bo ściga Cię coś niebywale groźnego.',
        opis:{
            h1:' ',
            a1:'Ta gra z gatunku horroru wciągnie Cię w swoją tajemniczą atmosferę rodem z film noir. Zanurz się głęboko w umysł detektyw Marie, usiłującej odkryć tajemnice swojej przeszłości, używając do tego wspomnień. Korzystaj z funkcji „koncentracji”, by spojrzeć oczami swojego oprawcy, starając się przetrwać trzymającą w napięciu grę w kotka i myszkę.',
            h2:'Cechy',
            a2:'Ucieknij swojemu oprawcy, rozszyfrowując niepokojącą historię Twojej przeszłości w trybie dla pojedynczego gracza.',
            h3:' ',
            a3:'Spersonalizuj i ulepsz swoją postać za pomocą ponad 40 zdolności i cech pasywnych.',
            h4:' ',
            a4:'Skanuj otoczenie i patrz oczami swojego oprawcy.',
            h5:' ',
            a5:'Losowo generowane mapy zapewnią, że żadna rozgrywka nie będzie taka sama',
        },
},

{
        id: '18',
        title:'Sense - A Cyberpunk Ghost Story',
        price: 69,
        img:'https://cdn1.epicgames.com/spt-assets/8943a7eaeca4489ea8ce2831238dbd16/download-sense--a-cyberpunk-ghost-story-offer-qhxl4.png?h=854&resize=1&w=640',
        zdjecia:{
            img2:'https://cdn1.epicgames.com/spt-assets/8943a7eaeca4489ea8ce2831238dbd16/sense--a-cyberpunk-ghost-story-1gp7i.jpg',
            img3:'https://cdn1.epicgames.com/spt-assets/8943a7eaeca4489ea8ce2831238dbd16/sense--a-cyberpunk-ghost-story-1teuo.jpg',
            img4:'https://cdn1.epicgames.com/spt-assets/8943a7eaeca4489ea8ce2831238dbd16/sense--a-cyberpunk-ghost-story-mu560.jpg',
            img5:'https://cdn1.epicgames.com/spt-assets/8943a7eaeca4489ea8ce2831238dbd16/sense--a-cyberpunk-ghost-story-dr21h.jpg',
            img6:'https://cdn1.epicgames.com/spt-assets/8943a7eaeca4489ea8ce2831238dbd16/sense--a-cyberpunk-ghost-story-1vazf.jpg', 
        },
        developer:'SUZAKU',
        Data_Wyd:'15.02.22',
        category:'horror',
        opis_glowny:'In 2083 Neo Hong Kong, a young woman named Mei-Lin Mak is dragged into a maelstrom of supernatural horror. Sense is a 2.5D horror game inspired by Clock Tower and Fatal Frame, mixing cyberpunk with traditional Cantonese folklore.',
        opis:{
            h1:'A RETURN TO CLASSIC HORROR!',
            a1:'Sense - 不祥的预感: A Cyberpunk Ghost Story is a 2.5D game inspired by Clock Tower and Fatal Frame. With careful attention to pacing, atmosphere and storytelling, Sense hopes to return the horror genre to its roots; celebrating the slow, fearful creep of dread instead of relying on over the top action and jump scares. The ghosts - as glitches on our reality - act as spiritual and paranormal threats, not monsters to be killed. The horror of our story comes from atmosphere and storytelling, not loud sound and artificial effects.',
            h2:'STORY',
            a2:'In 2083 Neo Hong Kong, a young woman named Mei-Lin Mak is dragged into a maelstrom of supernatural horror. As she peers deeper into a century old mystery, Mei will be forced to question her perception of reality and whether she trusts her cybernetic eyes. Under the neon lights of a cyberpunk dystopia, the ruins of the `Chong Sing Apartments` hides a bloody mystery illuminated by both the traditions of Chinese folklore, and the innovations of the industrial future. If there is any hope of escaping this nightmare, Mei-Lin must explore this complex, piecing together the stories of 14 lost souls',
            h3:'GAMEPLAY',
            a3:'You will need to search and examine every nook and cranny of the world, in order to progress. Some items may not be visible until specific chains are completed, and some items may be hidden from Mei`s cybernetic eyes at all times, as if spirited away by the ghosts stalking her. Some may require quick wit - and have urgent consequences',
            h4:'MORE FEATURES',
            a4:'Sense will be filled with secrets, but only some of them will be revealed in a single play through. Some secrets won`t be able to escape the spirit realm until the "Plus" appears',
        },
},

];

